version: '3.7'

services:
  yarn:
    image: node:11-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
      - yarncache:/workspace/.yarn-cache
    environment:
      - YARN_CACHE_FOLDER=/workspace/.yarn-cache
    entrypoint: yarn

  dashboard:
    image: node:11-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
    entrypoint: yarn dashboard:dev
    environment:
      - PORT=8010
    ports:
      - 8010:8010

volumes:
  modules:
  yarncache:
